### ISSUE TITLE
How do I find the UCM URL?

### ISSUE THREAD

**Issue by davidpomerenke** [tom-sherman/unison-vscode-ui#13]
Hi, I'm new to Unison, and I'm excited that you've written a plugin for VSCode for it, which looks very neat! 

When I first open the plugin and click the button "Configure Codebase", I'm asked to enter a "UCM URL". Where do I get this URL from?

I have already tried the URL that comes up when I start `ucm`and then type `ui`, which looks like `http://127.0.0.1:52685/5sXpIKK_OBvz1i0w/ui`, and I've tried it without the subpaths, but that doesn't work.

**Comment by tom-sherman** [comment]
Hey! I'm looking to improve this but for now you have to take the ui URL and replace `/ui` with `/api`.

eg. `http://127.0.0.1:52685/5sXpIKK_OBvz1i0w/api`.

**Comment by davidpomerenke** [comment]
Thank you, that works! 🥳
