### ISSUE TITLE
UCM URL instructions

### ISSUE THREAD

**Issue by edman** [tom-sherman/unison-vscode-ui#14]
This comment https://github.com/tom-sherman/unison-vscode-ui/issues/13#issuecomment-977858582 explains how to find the UCM URL for using with the extension.

Namely:
* run `ucm`
* use the `ui` command to open the codebase UI in the browser
* the link open in the browser is something like `http://127.0.0.1:55606/wwpl7ZIpIvhaNF5a/ui`
* replace the `/ui` ending with `/api`, as in `http://127.0.0.1:55606/wwpl7ZIpIvhaNF5a/api`

It seems you're trying to find a better solution but, meanwhile, can wee add these instructions to the readme?

I expect most users (like me) won't know what is that URL and where to find it, and a short nudge on readme would already go a long way.

**Comment by tom-sherman** [comment]
This is now done but I'll leave this open until I publish a new version.

**Comment by tom-sherman** [comment]
Released in 0.0.5
